language: node_js
node_js:
  - '11.1.0' # Developping under this version
  - 'node' # latest stable Node.js release
cache:
  directories:
    - 'node_modules'

env:
  global:
    # Code Climate reporter id
    secure: "UFqwYcy0S0hFP5eFZJgxrXyh7val02j91wXhH7EXLEd5FVTbjk++rczXrl8b9U6pP8iltplh2FVFp4GKDtxK5Bo8o4Zfe2Kxeo1m9ommd8ysk7p+TrY3FhmgMrstYoS27iDFZ+CMQr09Hn69lDYVzj+yONEHKKje/rsI5v3EAQ6SzRn/7RVXbdMpl7Ac8ZNoKgXcweIUjKPpJqxruCc/c4ZTJpgMo0RowwRGd1eBt6fd3fEXPAt8v1nWerQ5wjrGi/9NaQ3E6HP9YFnX139inlbQMZ1awWvNkgB1bd6Zhm22YQu17W+7oNrLK/rXbsZpDhovroBtEG5gzL89hFWfF97zPjUYrwlOvy1ldpC7mUfPNTjGZMrr8aZ4eTWP2Xdq9Ct4mRVYgi7u+4cqK7tvg04XWnpIn6sYuEKdhX+PJLgKsmOOIIbJPVHJ1W3DEjM/CKKNMjfHq1oSAYNCGHsxX4zOpbTfrfZ26zEr98ftCTWqwjf+HXN4bpjZJuu3BNur7sMS0ETtYIfa5pkka4b+XfKCP4OYTvOUOBh3Jo/ripHP+uOmfC5GAJMl0F1hTnLsiFVxHWOOPxap00JOkqJKUXyuojHgkjosXP61S2XhogXhwPS0eV8hVsh8i3khN/G//va6zPAf9/Ygf91B3nTLHOypXHbKU7gR170CsBigKeY="

before_script:
  # Code Climate: initialization
  # [TODO] test format to define
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  # Code Climate: sending report
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
after_script:
  # Code Climate: sending reporting only for "node"
  - |
    if [ "$TRAVIS_NODE_VERSION" == "node" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then 
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; 
    fi

notifications:
  slack:
    rooms:
      secure: "H3VVHih3xjL5tmWFKAWvl2MskKOpT4zIP6xPZQFwEwNESvx7PNXbNWVbDArv+nTsxL0LXNZYKoHLUZD9qMZZTMmK2HEBWifQ7UdXhLTqh6VlLuMxFnwa+EAA91bBfjHnLo06tCaLFFVesB1HO+/cDXGrFcYwNh6LQYSl+hQxj24CSdjMnzXx3yatq85V7obh98i/yZEoNbmkYItcuXwyNaziUxxxOb1xkb0rgEdOvJN7k79vyFhL0LDaCJH0rPx6KQ7NdRhzpzfIHEifBFzWfFbK7n0oy3cqTuEuLQB1Gsbw7LiwY0NMy4alO5y5INIUzATy+VvNzpbSHCzyV+Ey7ZxZxRI1ik7kIlqhRnDNDr45vBCxFCyk0s2/AVJQhvuAr3ho52vkF45SwfbcqxEp9ReSKCdBnnafnCEcr3TSvKI+nK2p0dU0HSBkdkWz1NLQHjgud+q+JlIfK8kDFDSTQqduB0MjSybS4TmAR2RV7OjY745qX+8HuOKiWRDTKsZJGtoB2KgpXsF2iAap80REdqj9IdDR37B0K8HaquN0Anw5sKNUXWSWbI6uburvgRz/+pqMglxdrvgx7ZxgTJ5hT60XefzMggMVA3fubzKii8QdOv3d2KMgGJfv+qa5WcoWfLlg4U3ouf5+qree1/3rpBqlbqi0NHm29OIv1FeLGU0="
    on_success: always
    on_failure: always
